name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  release_emulator:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        android: ["11.0"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    
    - name: Build
      run: ./release.sh build 11.0 ${RELEASE_VERSION}