name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  release_emulator:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        android: ["11.0"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    
    - name: Build and release
      run: |
        docker login -u=${{secrets.DOCKER_USERNAME}} -p=${{secrets.DOCKER_PASSWORD}}
        ./release.sh push ${{ matrix.android }} ${RELEASE_VERSION}
        docker logout